In [4]:
# Importando as bibliotecas pandas, matplolib e numpy

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

#Iportando o Arquivo CSV para a análise dos dados, 
#Abaixo será gerado um DataFrame para a manipulação usando o Pandas

analise_notas_df = pd.read_csv('analises_notas.csv')
df_atividade_4 = pd.read_csv('vpl_atividade_04_com_engajamento.csv')

In [5]:
analise_notas_df

,NOME_ALUNO,USERID,NotaCP,Nota1,Nota2,Nota3,Experiencia,Engajamento_ant
0,aluno 01,63,0.000,10.00,10.00,0.00,2,66.0
1,aluno 02,56,7.275,10.00,10.00,10.00,2,100.0
2,aluno 03,41,5.410,10.00,10.00,10.00,1,100.0
3,aluno 04,25,3.125,5.00,10.00,10.00,2,83.5
4,aluno 05,26,7.695,4.51,10.00,10.00,3,83.5
5,aluno 06,20,3.330,5.00,10.00,0.00,3,50.0
6,aluno 07,43,3.330,4.51,10.00,10.00,2,83.5
7,aluno 08,65,0.000,0.00,0.00,0.00,3,0.0
8,aluno 09,40,0.830,10.00,0.00,0.00,2,40.0
9,aluno 10,50,6.240,5.00,8.75,5.00,2,100.0
10,aluno 11,35,6.660,10.00,10.00,10.00,2,83.5
11,aluno 12,36,5.615,10.00,10.00,10.00,3,83.5
12,aluno 13,34,5.410,4.50,10.00,10.00,1,100.0
13,aluno 14,48,7.285,4.51,10.00,10.00,1,83.5
14,aluno 15,53,1.875,5.00,8.75,0.00,1,40.0
15,aluno 16,45,1.670,0.00,0.00,0.00,1,20.0
16,aluno 17,39,0.000,5.00,10.00,10.00,3,66.5
17,aluno 18,38,5.830,10.00,10.00,8.75,4,100.0
18,aluno 19,54,4.795,6.25,10.00,5.00,2,83.5
19,aluno 20,30,4.375,5.00,10.00,8.75,2,100.0
20,aluno 21,22,6.445,10.00,10.00,10.00,2,100.0
21,aluno 22,49,5.830,4.51,10.00,10.00,3,100.0
22,aluno 23,44,4.514,0.00,10.00,0.00,2,50.0
23,aluno 24,46,1.455,10.00,10.00,10.00,2,83.5
24,aluno 25,51,4.375,5.00,8.75,0.00,1,40.0
25,aluno 26,57,0.000,5.00,10.00,10.00,4,83.5
26,aluno 27,27,4.590,5.00,8.75,10.00,1,83.5
27,aluno 28,60,0.000,0.00,0.00,0.00,1,0.0
28,aluno 29,21,5.205,6.25,10.00,10.00,3,100.0
29,aluno 30,18,4.505,10.00,10.00,10.00,2,83.5
30,aluno 31,23,4.505,4.51,10.00,10.00,2,83.5
31,aluno 32,29,4.580,5.00,10.00,5.00,2,83.5
32,aluno 33,31,4.514,8.75,10.00,0.00,2,50.0
33,aluno 34,37,3.750,5.00,10.00,5.00,1,100.0
34,aluno 35,47,1.875,0.00,10.00,0.00,1,50.0
35,aluno 36,42,2.920,4.51,10.00,10.00,1,100.0
36,aluno 37,52,5.820,10.00,10.00,0.00,1,50.0
37,aluno 38,28,3.955,10.00,10.00,10.00,3,100.0

In [6]:
df_atividade_4

,NOME_ALUNO,Questão 01,Questão 02,Questão 03,Questão 04,Questão 05,Questão 06,Questão 07,Questão 08,Questão 09,...,Questão 23,Questão 24,Questão 25,Questão 26,Questão 27,Questão DESAFIO!,Media_Notas,ENTREGAS_NO_PRAZO,TOTAL_ENTREGAS,TAXA_ENGAJAMENTO
0,aluno 01,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,22,28,78.571429
1,aluno 02,10.0,10.0,10.0,10.0,0.0,0.0,10.0,10.0,10.0,...,10.0,10.0,0.0,10.0,10.0,10.0,8.928571,24,28,85.714286
2,aluno 03,0.0,10.0,10.0,10.0,0.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,8.928571,28,28,100.000000
3,aluno 04,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
4,aluno 05,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,26,28,92.857143
5,aluno 06,0.0,0.0,10.0,10.0,0.0,0.0,0.0,10.0,0.0,...,10.0,10.0,10.0,10.0,10.0,0.0,4.642857,28,28,100.000000
6,aluno 07,10.0,10.0,10.0,10.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.571429,20,26,71.428571
7,aluno 08,10.0,10.0,10.0,10.0,10.0,10.0,10.0,0.0,10.0,...,0.0,10.0,10.0,10.0,0.0,10.0,7.500000,26,28,92.857143
8,aluno 09,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
9,aluno 10,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,0.0,8.928571,28,28,100.000000
10,aluno 11,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,0.0,10.0,10.0,10.0,9.642857,27,28,96.428571
11,aluno 12,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
12,aluno 13,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
13,aluno 14,10.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.071429,3,3,10.714286
14,aluno 15,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.142857,22,22,78.571429
15,aluno 16,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
16,aluno 17,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,9.642857,26,28,92.857143
17,aluno 18,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,0.0,9.642857,27,27,96.428571
18,aluno 19,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
19,aluno 20,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
20,aluno 21,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
21,aluno 22,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,8.928571,28,28,100.000000
22,aluno 23,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,0.0,9.642857,27,27,96.428571
23,aluno 24,10.0,10.0,0.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,9.642857,28,28,100.000000
24,aluno 25,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
25,aluno 26,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,0.0,9.285714,27,27,96.428571
26,aluno 27,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
27,aluno 28,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
28,aluno 29,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,27,28,96.428571
29,aluno 30,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
30,aluno 31,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,23,28,82.142857
31,aluno 32,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,0.0,9.642857,24,27,85.714286
32,aluno 33,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
33,aluno 34,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,0.0,9.642857,26,27,92.857143
34,aluno 35,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,0.0,9.642857,27,27,96.428571
35,aluno 36,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000
36,aluno 37,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,0.0,9.642857,27,27,96.428571
37,aluno 38,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.000000,28,28,100.000000

In [13]:
analise_notas_df = analise_notas_df.merge(df_atividade_4[['NOME_ALUNO', 'Media_Notas']], on='NOME_ALUNO', how='left', suffixes=('_atividade_4', '_atividade_4'))

analise_notas_df

,NOME_ALUNO,USERID,NotaCP,Nota1,Nota2,Nota3,Experiencia,Engajamento_ant,engajamento_n4,engajamento_n4_media,Media_Notas
0,aluno 01,63,0.000,10.00,10.00,0.00,2,66.0,78.571429,72.285714,10.000000
1,aluno 02,56,7.275,10.00,10.00,10.00,2,100.0,85.714286,92.857143,8.928571
2,aluno 03,41,5.410,10.00,10.00,10.00,1,100.0,100.000000,100.000000,8.928571
3,aluno 04,25,3.125,5.00,10.00,10.00,2,83.5,100.000000,91.750000,10.000000
4,aluno 05,26,7.695,4.51,10.00,10.00,3,83.5,92.857143,88.178571,10.000000
5,aluno 06,20,3.330,5.00,10.00,0.00,3,50.0,100.000000,75.000000,4.642857
6,aluno 07,43,3.330,4.51,10.00,10.00,2,83.5,71.428571,77.464286,3.571429
7,aluno 08,65,0.000,0.00,0.00,0.00,3,0.0,92.857143,46.428571,7.500000
8,aluno 09,40,0.830,10.00,0.00,0.00,2,40.0,100.000000,70.000000,10.000000
9,aluno 10,50,6.240,5.00,8.75,5.00,2,100.0,100.000000,100.000000,8.928571
10,aluno 11,35,6.660,10.00,10.00,10.00,2,83.5,96.428571,89.964286,9.642857
11,aluno 12,36,5.615,10.00,10.00,10.00,3,83.5,100.000000,91.750000,10.000000
12,aluno 13,34,5.410,4.50,10.00,10.00,1,100.0,100.000000,100.000000,10.000000
13,aluno 14,48,7.285,4.51,10.00,10.00,1,83.5,10.714286,47.107143,1.071429
14,aluno 15,53,1.875,5.00,8.75,0.00,1,40.0,78.571429,59.285714,7.142857
15,aluno 16,45,1.670,0.00,0.00,0.00,1,20.0,100.000000,60.000000,10.000000
16,aluno 17,39,0.000,5.00,10.00,10.00,3,66.5,92.857143,79.678571,9.642857
17,aluno 18,38,5.830,10.00,10.00,8.75,4,100.0,96.428571,98.214286,9.642857
18,aluno 19,54,4.795,6.25,10.00,5.00,2,83.5,100.000000,91.750000,10.000000
19,aluno 20,30,4.375,5.00,10.00,8.75,2,100.0,100.000000,100.000000,10.000000
20,aluno 21,22,6.445,10.00,10.00,10.00,2,100.0,100.000000,100.000000,10.000000
21,aluno 22,49,5.830,4.51,10.00,10.00,3,100.0,100.000000,100.000000,8.928571
22,aluno 23,44,4.514,0.00,10.00,0.00,2,50.0,96.428571,73.214286,9.642857
23,aluno 24,46,1.455,10.00,10.00,10.00,2,83.5,100.000000,91.750000,9.642857
24,aluno 25,51,4.375,5.00,8.75,0.00,1,40.0,100.000000,70.000000,10.000000
25,aluno 26,57,0.000,5.00,10.00,10.00,4,83.5,96.428571,89.964286,9.285714
26,aluno 27,27,4.590,5.00,8.75,10.00,1,83.5,100.000000,91.750000,10.000000
27,aluno 28,60,0.000,0.00,0.00,0.00,1,0.0,100.000000,50.000000,10.000000
28,aluno 29,21,5.205,6.25,10.00,10.00,3,100.0,96.428571,98.214286,10.000000
29,aluno 30,18,4.505,10.00,10.00,10.00,2,83.5,100.000000,91.750000,10.000000
30,aluno 31,23,4.505,4.51,10.00,10.00,2,83.5,82.142857,82.821429,10.000000
31,aluno 32,29,4.580,5.00,10.00,5.00,2,83.5,85.714286,84.607143,9.642857
32,aluno 33,31,4.514,8.75,10.00,0.00,2,50.0,100.000000,75.000000,10.000000
33,aluno 34,37,3.750,5.00,10.00,5.00,1,100.0,92.857143,96.428571,9.642857
34,aluno 35,47,1.875,0.00,10.00,0.00,1,50.0,96.428571,73.214286,9.642857
35,aluno 36,42,2.920,4.51,10.00,10.00,1,100.0,100.000000,100.000000,10.000000
36,aluno 37,52,5.820,10.00,10.00,0.00,1,50.0,96.428571,73.214286,9.642857
37,aluno 38,28,3.955,10.00,10.00,10.00,3,100.0,100.000000,100.000000,10.000000

In [12]:
analise_notas_df.rename(columns={'Media_Notas': 'Nota4'}, inplace=True)

analise_notas_df

,NOME_ALUNO,USERID,NotaCP,Nota1,Nota2,Nota3,Experiencia,Engajamento_ant,engajamento_n4,engajamento_n4_media
0,aluno 01,63,0.000,10.00,10.00,0.00,2,66.0,78.571429,72.285714
1,aluno 02,56,7.275,10.00,10.00,10.00,2,100.0,85.714286,92.857143
2,aluno 03,41,5.410,10.00,10.00,10.00,1,100.0,100.000000,100.000000
3,aluno 04,25,3.125,5.00,10.00,10.00,2,83.5,100.000000,91.750000
4,aluno 05,26,7.695,4.51,10.00,10.00,3,83.5,92.857143,88.178571
5,aluno 06,20,3.330,5.00,10.00,0.00,3,50.0,100.000000,75.000000
6,aluno 07,43,3.330,4.51,10.00,10.00,2,83.5,71.428571,77.464286
7,aluno 08,65,0.000,0.00,0.00,0.00,3,0.0,92.857143,46.428571
8,aluno 09,40,0.830,10.00,0.00,0.00,2,40.0,100.000000,70.000000
9,aluno 10,50,6.240,5.00,8.75,5.00,2,100.0,100.000000,100.000000
10,aluno 11,35,6.660,10.00,10.00,10.00,2,83.5,96.428571,89.964286
11,aluno 12,36,5.615,10.00,10.00,10.00,3,83.5,100.000000,91.750000
12,aluno 13,34,5.410,4.50,10.00,10.00,1,100.0,100.000000,100.000000
13,aluno 14,48,7.285,4.51,10.00,10.00,1,83.5,10.714286,47.107143
14,aluno 15,53,1.875,5.00,8.75,0.00,1,40.0,78.571429,59.285714
15,aluno 16,45,1.670,0.00,0.00,0.00,1,20.0,100.000000,60.000000
16,aluno 17,39,0.000,5.00,10.00,10.00,3,66.5,92.857143,79.678571
17,aluno 18,38,5.830,10.00,10.00,8.75,4,100.0,96.428571,98.214286
18,aluno 19,54,4.795,6.25,10.00,5.00,2,83.5,100.000000,91.750000
19,aluno 20,30,4.375,5.00,10.00,8.75,2,100.0,100.000000,100.000000
20,aluno 21,22,6.445,10.00,10.00,10.00,2,100.0,100.000000,100.000000
21,aluno 22,49,5.830,4.51,10.00,10.00,3,100.0,100.000000,100.000000
22,aluno 23,44,4.514,0.00,10.00,0.00,2,50.0,96.428571,73.214286
23,aluno 24,46,1.455,10.00,10.00,10.00,2,83.5,100.000000,91.750000
24,aluno 25,51,4.375,5.00,8.75,0.00,1,40.0,100.000000,70.000000
25,aluno 26,57,0.000,5.00,10.00,10.00,4,83.5,96.428571,89.964286
26,aluno 27,27,4.590,5.00,8.75,10.00,1,83.5,100.000000,91.750000
27,aluno 28,60,0.000,0.00,0.00,0.00,1,0.0,100.000000,50.000000
28,aluno 29,21,5.205,6.25,10.00,10.00,3,100.0,96.428571,98.214286
29,aluno 30,18,4.505,10.00,10.00,10.00,2,83.5,100.000000,91.750000
30,aluno 31,23,4.505,4.51,10.00,10.00,2,83.5,82.142857,82.821429
31,aluno 32,29,4.580,5.00,10.00,5.00,2,83.5,85.714286,84.607143
32,aluno 33,31,4.514,8.75,10.00,0.00,2,50.0,100.000000,75.000000
33,aluno 34,37,3.750,5.00,10.00,5.00,1,100.0,92.857143,96.428571
34,aluno 35,47,1.875,0.00,10.00,0.00,1,50.0,96.428571,73.214286
35,aluno 36,42,2.920,4.51,10.00,10.00,1,100.0,100.000000,100.000000
36,aluno 37,52,5.820,10.00,10.00,0.00,1,50.0,96.428571,73.214286
37,aluno 38,28,3.955,10.00,10.00,10.00,3,100.0,100.000000,100.000000

In [7]:
analise_notas_df = analise_notas_df.merge(df_atividade_4[['NOME_ALUNO', 'TAXA_ENGAJAMENTO']], on='NOME_ALUNO', how='left', suffixes=('_atividade_4', '_atividade_4'))

analise_notas_df

,NOME_ALUNO,USERID,NotaCP,Nota1,Nota2,Nota3,Experiencia,Engajamento_ant,TAXA_ENGAJAMENTO
0,aluno 01,63,0.000,10.00,10.00,0.00,2,66.0,78.571429
1,aluno 02,56,7.275,10.00,10.00,10.00,2,100.0,85.714286
2,aluno 03,41,5.410,10.00,10.00,10.00,1,100.0,100.000000
3,aluno 04,25,3.125,5.00,10.00,10.00,2,83.5,100.000000
4,aluno 05,26,7.695,4.51,10.00,10.00,3,83.5,92.857143
5,aluno 06,20,3.330,5.00,10.00,0.00,3,50.0,100.000000
6,aluno 07,43,3.330,4.51,10.00,10.00,2,83.5,71.428571
7,aluno 08,65,0.000,0.00,0.00,0.00,3,0.0,92.857143
8,aluno 09,40,0.830,10.00,0.00,0.00,2,40.0,100.000000
9,aluno 10,50,6.240,5.00,8.75,5.00,2,100.0,100.000000
10,aluno 11,35,6.660,10.00,10.00,10.00,2,83.5,96.428571
11,aluno 12,36,5.615,10.00,10.00,10.00,3,83.5,100.000000
12,aluno 13,34,5.410,4.50,10.00,10.00,1,100.0,100.000000
13,aluno 14,48,7.285,4.51,10.00,10.00,1,83.5,10.714286
14,aluno 15,53,1.875,5.00,8.75,0.00,1,40.0,78.571429
15,aluno 16,45,1.670,0.00,0.00,0.00,1,20.0,100.000000
16,aluno 17,39,0.000,5.00,10.00,10.00,3,66.5,92.857143
17,aluno 18,38,5.830,10.00,10.00,8.75,4,100.0,96.428571
18,aluno 19,54,4.795,6.25,10.00,5.00,2,83.5,100.000000
19,aluno 20,30,4.375,5.00,10.00,8.75,2,100.0,100.000000
20,aluno 21,22,6.445,10.00,10.00,10.00,2,100.0,100.000000
21,aluno 22,49,5.830,4.51,10.00,10.00,3,100.0,100.000000
22,aluno 23,44,4.514,0.00,10.00,0.00,2,50.0,96.428571
23,aluno 24,46,1.455,10.00,10.00,10.00,2,83.5,100.000000
24,aluno 25,51,4.375,5.00,8.75,0.00,1,40.0,100.000000
25,aluno 26,57,0.000,5.00,10.00,10.00,4,83.5,96.428571
26,aluno 27,27,4.590,5.00,8.75,10.00,1,83.5,100.000000
27,aluno 28,60,0.000,0.00,0.00,0.00,1,0.0,100.000000
28,aluno 29,21,5.205,6.25,10.00,10.00,3,100.0,96.428571
29,aluno 30,18,4.505,10.00,10.00,10.00,2,83.5,100.000000
30,aluno 31,23,4.505,4.51,10.00,10.00,2,83.5,82.142857
31,aluno 32,29,4.580,5.00,10.00,5.00,2,83.5,85.714286
32,aluno 33,31,4.514,8.75,10.00,0.00,2,50.0,100.000000
33,aluno 34,37,3.750,5.00,10.00,5.00,1,100.0,92.857143
34,aluno 35,47,1.875,0.00,10.00,0.00,1,50.0,96.428571
35,aluno 36,42,2.920,4.51,10.00,10.00,1,100.0,100.000000
36,aluno 37,52,5.820,10.00,10.00,0.00,1,50.0,96.428571
37,aluno 38,28,3.955,10.00,10.00,10.00,3,100.0,100.000000

In [8]:
analise_notas_df.rename(columns={'TAXA_ENGAJAMENTO': 'engajamento_n4'}, inplace=True)

analise_notas_df

,NOME_ALUNO,USERID,NotaCP,Nota1,Nota2,Nota3,Experiencia,Engajamento_ant,engajamento_n4
0,aluno 01,63,0.000,10.00,10.00,0.00,2,66.0,78.571429
1,aluno 02,56,7.275,10.00,10.00,10.00,2,100.0,85.714286
2,aluno 03,41,5.410,10.00,10.00,10.00,1,100.0,100.000000
3,aluno 04,25,3.125,5.00,10.00,10.00,2,83.5,100.000000
4,aluno 05,26,7.695,4.51,10.00,10.00,3,83.5,92.857143
5,aluno 06,20,3.330,5.00,10.00,0.00,3,50.0,100.000000
6,aluno 07,43,3.330,4.51,10.00,10.00,2,83.5,71.428571
7,aluno 08,65,0.000,0.00,0.00,0.00,3,0.0,92.857143
8,aluno 09,40,0.830,10.00,0.00,0.00,2,40.0,100.000000
9,aluno 10,50,6.240,5.00,8.75,5.00,2,100.0,100.000000
10,aluno 11,35,6.660,10.00,10.00,10.00,2,83.5,96.428571
11,aluno 12,36,5.615,10.00,10.00,10.00,3,83.5,100.000000
12,aluno 13,34,5.410,4.50,10.00,10.00,1,100.0,100.000000
13,aluno 14,48,7.285,4.51,10.00,10.00,1,83.5,10.714286
14,aluno 15,53,1.875,5.00,8.75,0.00,1,40.0,78.571429
15,aluno 16,45,1.670,0.00,0.00,0.00,1,20.0,100.000000
16,aluno 17,39,0.000,5.00,10.00,10.00,3,66.5,92.857143
17,aluno 18,38,5.830,10.00,10.00,8.75,4,100.0,96.428571
18,aluno 19,54,4.795,6.25,10.00,5.00,2,83.5,100.000000
19,aluno 20,30,4.375,5.00,10.00,8.75,2,100.0,100.000000
20,aluno 21,22,6.445,10.00,10.00,10.00,2,100.0,100.000000
21,aluno 22,49,5.830,4.51,10.00,10.00,3,100.0,100.000000
22,aluno 23,44,4.514,0.00,10.00,0.00,2,50.0,96.428571
23,aluno 24,46,1.455,10.00,10.00,10.00,2,83.5,100.000000
24,aluno 25,51,4.375,5.00,8.75,0.00,1,40.0,100.000000
25,aluno 26,57,0.000,5.00,10.00,10.00,4,83.5,96.428571
26,aluno 27,27,4.590,5.00,8.75,10.00,1,83.5,100.000000
27,aluno 28,60,0.000,0.00,0.00,0.00,1,0.0,100.000000
28,aluno 29,21,5.205,6.25,10.00,10.00,3,100.0,96.428571
29,aluno 30,18,4.505,10.00,10.00,10.00,2,83.5,100.000000
30,aluno 31,23,4.505,4.51,10.00,10.00,2,83.5,82.142857
31,aluno 32,29,4.580,5.00,10.00,5.00,2,83.5,85.714286
32,aluno 33,31,4.514,8.75,10.00,0.00,2,50.0,100.000000
33,aluno 34,37,3.750,5.00,10.00,5.00,1,100.0,92.857143
34,aluno 35,47,1.875,0.00,10.00,0.00,1,50.0,96.428571
35,aluno 36,42,2.920,4.51,10.00,10.00,1,100.0,100.000000
36,aluno 37,52,5.820,10.00,10.00,0.00,1,50.0,96.428571
37,aluno 38,28,3.955,10.00,10.00,10.00,3,100.0,100.000000

In [9]:
analise_notas_df['engajamento_n4_media'] = (analise_notas_df['Engajamento_ant'] + analise_notas_df['engajamento_n4'])/2

analise_notas_df

,NOME_ALUNO,USERID,NotaCP,Nota1,Nota2,Nota3,Experiencia,Engajamento_ant,engajamento_n4,engajamento_n4_media
0,aluno 01,63,0.000,10.00,10.00,0.00,2,66.0,78.571429,72.285714
1,aluno 02,56,7.275,10.00,10.00,10.00,2,100.0,85.714286,92.857143
2,aluno 03,41,5.410,10.00,10.00,10.00,1,100.0,100.000000,100.000000
3,aluno 04,25,3.125,5.00,10.00,10.00,2,83.5,100.000000,91.750000
4,aluno 05,26,7.695,4.51,10.00,10.00,3,83.5,92.857143,88.178571
5,aluno 06,20,3.330,5.00,10.00,0.00,3,50.0,100.000000,75.000000
6,aluno 07,43,3.330,4.51,10.00,10.00,2,83.5,71.428571,77.464286
7,aluno 08,65,0.000,0.00,0.00,0.00,3,0.0,92.857143,46.428571
8,aluno 09,40,0.830,10.00,0.00,0.00,2,40.0,100.000000,70.000000
9,aluno 10,50,6.240,5.00,8.75,5.00,2,100.0,100.000000,100.000000
10,aluno 11,35,6.660,10.00,10.00,10.00,2,83.5,96.428571,89.964286
11,aluno 12,36,5.615,10.00,10.00,10.00,3,83.5,100.000000,91.750000
12,aluno 13,34,5.410,4.50,10.00,10.00,1,100.0,100.000000,100.000000
13,aluno 14,48,7.285,4.51,10.00,10.00,1,83.5,10.714286,47.107143
14,aluno 15,53,1.875,5.00,8.75,0.00,1,40.0,78.571429,59.285714
15,aluno 16,45,1.670,0.00,0.00,0.00,1,20.0,100.000000,60.000000
16,aluno 17,39,0.000,5.00,10.00,10.00,3,66.5,92.857143,79.678571
17,aluno 18,38,5.830,10.00,10.00,8.75,4,100.0,96.428571,98.214286
18,aluno 19,54,4.795,6.25,10.00,5.00,2,83.5,100.000000,91.750000
19,aluno 20,30,4.375,5.00,10.00,8.75,2,100.0,100.000000,100.000000
20,aluno 21,22,6.445,10.00,10.00,10.00,2,100.0,100.000000,100.000000
21,aluno 22,49,5.830,4.51,10.00,10.00,3,100.0,100.000000,100.000000
22,aluno 23,44,4.514,0.00,10.00,0.00,2,50.0,96.428571,73.214286
23,aluno 24,46,1.455,10.00,10.00,10.00,2,83.5,100.000000,91.750000
24,aluno 25,51,4.375,5.00,8.75,0.00,1,40.0,100.000000,70.000000
25,aluno 26,57,0.000,5.00,10.00,10.00,4,83.5,96.428571,89.964286
26,aluno 27,27,4.590,5.00,8.75,10.00,1,83.5,100.000000,91.750000
27,aluno 28,60,0.000,0.00,0.00,0.00,1,0.0,100.000000,50.000000
28,aluno 29,21,5.205,6.25,10.00,10.00,3,100.0,96.428571,98.214286
29,aluno 30,18,4.505,10.00,10.00,10.00,2,83.5,100.000000,91.750000
30,aluno 31,23,4.505,4.51,10.00,10.00,2,83.5,82.142857,82.821429
31,aluno 32,29,4.580,5.00,10.00,5.00,2,83.5,85.714286,84.607143
32,aluno 33,31,4.514,8.75,10.00,0.00,2,50.0,100.000000,75.000000
33,aluno 34,37,3.750,5.00,10.00,5.00,1,100.0,92.857143,96.428571
34,aluno 35,47,1.875,0.00,10.00,0.00,1,50.0,96.428571,73.214286
35,aluno 36,42,2.920,4.51,10.00,10.00,1,100.0,100.000000,100.000000
36,aluno 37,52,5.820,10.00,10.00,0.00,1,50.0,96.428571,73.214286
37,aluno 38,28,3.955,10.00,10.00,10.00,3,100.0,100.000000,100.000000

In [11]:
df_atividade_5 = pd.read_csv('vpl_atividade_05_com_engajamento.csv')

df_atividade_5

,NOME_ALUNO,Questão 1,Questão 10,Questão 11,Questão 12,Questão 14,Questão 15,Questão 16,Questão 17,Questão 18,...,Questão 4,Questão 5,Questão 6,Questão 7,Questão 8,Questão 9,Media_Notas,ENTREGAS_NO_PRAZO,TOTAL_ENTREGAS,TAXA_ENGAJAMENTO
0,Alexandre Henrique Oliveira de Sousa,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,0.0,...,10.0,10.0,10.00,10.00,10.0,10.00,9.411765,16,16,94.117647
1,Alisson vaz silva,10.00,10.0,10.0,0.0,8.0,10.00,0.00,8.0,10.0,...,10.0,10.0,6.67,10.00,10.0,6.67,8.196471,17,17,100.000000
2,Antonio Wills da Silva Santos,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,10.000000,17,17,100.000000
3,Carlos Eduardo Lima Coutinho,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,10.000000,17,17,100.000000
4,Crisfieldy Aristodenes Feitoza Ribeiro,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,10.000000,16,17,94.117647
5,Danielly dos Santos Almeida,6.67,10.0,10.0,10.0,10.0,10.00,10.00,10.0,7.5,...,10.0,10.0,10.00,10.00,5.0,10.00,9.362941,17,17,100.000000
6,Debriane da Silva Conceição,3.33,5.0,10.0,10.0,2.0,10.00,1.43,8.0,7.5,...,5.0,10.0,6.67,6.67,10.0,6.67,6.015882,12,17,70.588235
7,Durval Veloso Barbosa Filho,10.00,10.0,10.0,10.0,10.0,8.75,8.57,8.0,10.0,...,10.0,10.0,10.00,10.00,10.0,6.67,9.528824,14,17,82.352941
8,Evelly Victory Vieira Pinto,10.00,10.0,0.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,9.411765,16,16,94.117647
9,Francisco Leonel Ferreira dos Santos,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,10.000000,17,17,100.000000
10,Gabriel Antonio Assunção Oliveira,10.00,10.0,10.0,10.0,0.0,10.00,10.00,10.0,0.0,...,10.0,10.0,10.00,10.00,10.0,10.00,8.529412,15,15,88.235294
11,Gabriel Viana Da Costa,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,9.705882,17,17,100.000000
12,Guilherme Oliveira de Menezes,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,10.000000,17,17,100.000000
13,Gustavo Neves,10.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,...,10.0,10.0,10.00,10.00,0.0,0.00,4.117647,7,7,41.176471
14,Heráclito Thiago de Castro Santos,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,10.000000,17,17,100.000000
15,Hipócrates Augusto Soares Brandão Galvão de Ca...,10.00,10.0,10.0,7.5,0.0,10.00,0.00,10.0,0.0,...,10.0,10.0,10.00,10.00,10.0,10.00,8.088235,16,16,94.117647
16,Isaac Levi Oliveira Chaves,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,10.000000,11,17,64.705882
17,Jonas Davi Nogueira Sena,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,5.0,...,10.0,10.0,10.00,10.00,5.0,10.00,9.117647,17,17,100.000000
18,José Cássios Costa Torres,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,10.000000,16,17,94.117647
19,Juan Pablo de sousa silva,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,0.0,...,10.0,10.0,10.00,10.00,10.0,10.00,9.411765,16,16,94.117647
20,Lara Emanuelly da Silva Santos,10.00,10.0,8.0,7.5,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,9.735294,16,17,94.117647
21,Loyse Kelly Cardoso Diniz,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,7.5,...,10.0,10.0,10.00,10.00,10.0,10.00,9.852941,17,17,100.000000
22,Lucas Eduardo Lima Da Silva,10.00,10.0,10.0,10.0,10.0,10.00,10.00,0.0,0.0,...,10.0,10.0,10.00,10.00,10.0,10.00,8.823529,15,15,88.235294
23,Luis Eduardo Martins Formiga,10.00,10.0,10.0,0.0,0.0,10.00,0.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,8.235294,11,15,64.705882
24,Luis Felipe Assunção Pereira,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,6.67,9.510000,16,17,94.117647
25,Mickaela evely Sousa de Freitas,10.00,10.0,8.0,7.5,0.0,0.00,0.00,0.0,10.0,...,10.0,10.0,0.00,10.00,10.0,6.67,6.598235,11,12,64.705882
26,Neudson Gabriel C. C. Branco,6.67,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,9.804118,17,17,100.000000
27,Pedro Victor Soares da Silva Araújo,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,10.000000,17,17,100.000000
28,Raislan Ítalo de Sousa da Silva,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,10.000000,16,17,94.117647
29,Randerson Sousa de Sá Nunes,6.67,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,...,10.0,10.0,10.00,0.00,0.0,0.00,3.333529,5,6,29.411765
30,Roberto Guilhon Rosa Filho,6.67,10.0,10.0,2.5,0.0,0.00,0.00,10.0,0.0,...,10.0,10.0,10.00,10.00,10.0,10.00,6.421765,1,12,5.882353
31,Samuel Ryan da Fonseca Anunciação,10.00,10.0,10.0,7.5,10.0,8.75,7.14,8.0,7.5,...,10.0,10.0,10.00,10.00,10.0,6.67,9.150588,17,17,100.000000
32,Saymon Italo Cordeiro de Moura,10.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,...,10.0,0.0,0.00,0.00,0.0,0.00,2.352941,5,5,29.411765
33,Victor Emanuel Cunha Morais,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,10.000000,16,17,94.117647
34,Willian Jorge Sousa Furtado,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.0,10.0,...,10.0,10.0,6.67,10.00,10.0,10.00,9.510000,17,17,100.000000
35,Ycaro Yan Lourenço Santos,6.67,10.0,0.0,2.5,0.0,0.00,0.00,8.0,5.0,...,10.0,10.0,6.67,3.33,10.0,6.67,5.520000,16,16,94.117647
36,Ávila da Conceição Araújo,0.00,10.0,10.0,10.0,10.0,10.00,7.14,10.0,10.0,...,10.0,10.0,10.00,10.00,10.0,10.00,9.243529,16,16,94.117647

In [12]:
analise_notas_df = analise_notas_df.merge(df_atividade_5[['NOME_ALUNO', 'Media_Notas']], 
                                          on='NOME_ALUNO', how='left', suffixes=('_atividade_5', '_atividade_5'))

analise_notas_df.rename(columns={'Media_Notas': 'Nota5'}, inplace=True)


analise_notas_df = analise_notas_df.merge(df_atividade_4[['NOME_ALUNO', 'TAXA_ENGAJAMENTO']], 
                                          on='NOME_ALUNO', how='left', suffixes=('_atividade_5', '_atividade_5'))

analise_notas_df.rename(columns={'TAXA_ENGAJAMENTO': 'engajamento_n5'}, inplace=True)

analise_notas_df['engajamento_n5_media'] = (analise_notas_df['engajamento_n4'] + analise_notas_df['engajamento_n5'])/2

analise_notas_df

,NOME_ALUNO,USERID,NotaCP,Nota1,Nota2,Nota3,Experiencia,Engajamento_ant,Nota4,engajamento_n4,engajamento_n4_media,Nota5,engajamento_n5,engajamento_n5_media
0,Alexandre Henrique Oliveira de Sousa,63,0.000,10.00,10.00,0.00,2,66.0,10.000000,78.571429,72.285714,9.411765,78.571429,78.571429
1,Alisson vaz silva,56,7.275,10.00,10.00,10.00,2,100.0,8.928571,85.714286,92.857143,8.196471,85.714286,85.714286
2,Antonio Wills da Silva Santos,41,5.410,10.00,10.00,10.00,1,100.0,8.928571,100.000000,100.000000,10.000000,100.000000,100.000000
3,Ávila da Conceição Araújo,25,3.125,5.00,10.00,10.00,2,83.5,10.000000,100.000000,91.750000,9.243529,100.000000,100.000000
4,Carlos Eduardo Lima Coutinho,26,7.695,4.51,10.00,10.00,3,83.5,10.000000,100.000000,91.750000,10.000000,100.000000,100.000000
5,Crisfieldy Aristodenes Feitoza Ribeiro,20,3.330,5.00,10.00,0.00,3,50.0,10.000000,92.857143,71.428571,10.000000,92.857143,92.857143
6,Danielly dos Santos Almeida,43,3.330,4.51,10.00,10.00,2,83.5,4.642857,100.000000,91.750000,9.362941,100.000000,100.000000
7,Debriane da Silva Conceição,65,0.000,0.00,0.00,0.00,3,0.0,3.571429,71.428571,35.714286,6.015882,71.428571,71.428571
8,Durval Veloso Barbosa Filho,40,0.830,10.00,0.00,0.00,2,40.0,7.500000,92.857143,66.428571,9.528824,92.857143,92.857143
9,Evelly Victory Vieira Pinto,50,6.240,5.00,8.75,5.00,2,100.0,10.000000,100.000000,100.000000,9.411765,100.000000,100.000000
10,Francisco Leonel Ferreira dos Santos,35,6.660,10.00,10.00,10.00,2,83.5,8.928571,100.000000,91.750000,10.000000,100.000000,100.000000
11,Gabriel Antonio Assunção Oliveira,36,5.615,10.00,10.00,10.00,3,83.5,9.642857,96.428571,89.964286,8.529412,96.428571,96.428571
12,Gabriel Viana Da Costa,34,5.410,4.50,10.00,10.00,1,100.0,10.000000,100.000000,100.000000,9.705882,100.000000,100.000000
13,Guilherme Oliveira de Menezes,48,7.285,4.51,10.00,10.00,1,83.5,10.000000,100.000000,91.750000,10.000000,100.000000,100.000000
14,Gustavo Marinho Santos,53,1.875,5.00,8.75,0.00,1,40.0,1.071429,10.714286,25.357143,NaN,10.714286,10.714286
15,Gustavo Neves,45,1.670,0.00,0.00,0.00,1,20.0,7.142857,78.571429,49.285714,4.117647,78.571429,78.571429
16,Heráclito Thiago de Castro Santos,39,0.000,5.00,10.00,10.00,3,66.5,10.000000,100.000000,83.250000,10.000000,100.000000,100.000000
17,Hipócrates Augusto Soares Brandão Galvão de Ca...,38,5.830,10.00,10.00,8.75,4,100.0,9.642857,92.857143,96.428571,8.088235,92.857143,92.857143
18,Isaac Levi Oliveira Chaves,54,4.795,6.25,10.00,5.00,2,83.5,9.642857,96.428571,89.964286,10.000000,96.428571,96.428571
19,Jonas Davi Nogueira Sena,30,4.375,5.00,10.00,8.75,2,100.0,10.000000,100.000000,100.000000,9.117647,100.000000,100.000000
20,José Cássios Costa Torres,22,6.445,10.00,10.00,10.00,2,100.0,10.000000,100.000000,100.000000,10.000000,100.000000,100.000000
21,Juan Pablo de sousa silva,49,5.830,4.51,10.00,10.00,3,100.0,10.000000,100.000000,100.000000,9.411765,100.000000,100.000000
22,Lara Emanuelly da Silva Santos,44,4.514,0.00,10.00,0.00,2,50.0,8.928571,100.000000,75.000000,9.735294,100.000000,100.000000
23,Loyse Kelly Cardoso Diniz,46,1.455,10.00,10.00,10.00,2,83.5,9.642857,96.428571,89.964286,9.852941,96.428571,96.428571
24,Lucas Eduardo Lima Da Silva,51,4.375,5.00,8.75,0.00,1,40.0,9.642857,100.000000,70.000000,8.823529,100.000000,100.000000
25,Luis Eduardo Martins Formiga,57,0.000,5.00,10.00,10.00,4,83.5,10.000000,100.000000,91.750000,8.235294,100.000000,100.000000
26,Luis Felipe Assunção Pereira,27,4.590,5.00,8.75,10.00,1,83.5,9.285714,96.428571,89.964286,9.510000,96.428571,96.428571
27,Mickaela evely Sousa de Freitas,60,0.000,0.00,0.00,0.00,1,0.0,10.000000,100.000000,50.000000,6.598235,100.000000,100.000000
28,Neudson Gabriel C. C. Branco,21,5.205,6.25,10.00,10.00,3,100.0,10.000000,100.000000,100.000000,9.804118,100.000000,100.000000
29,Pedro Victor Soares da Silva Araújo,18,4.505,10.00,10.00,10.00,2,83.5,10.000000,96.428571,89.964286,10.000000,96.428571,96.428571
30,Raislan Ítalo de Sousa da Silva,23,4.505,4.51,10.00,10.00,2,83.5,10.000000,100.000000,91.750000,10.000000,100.000000,100.000000
31,Randerson Sousa de Sá Nunes,29,4.580,5.00,10.00,5.00,2,83.5,10.000000,82.142857,82.821429,3.333529,82.142857,82.142857
32,Roberto Guilhon Rosa Filho,31,4.514,8.75,10.00,0.00,2,50.0,9.642857,85.714286,67.857143,6.421765,85.714286,85.714286
33,Samuel Ryan da Fonseca Anunciação,37,3.750,5.00,10.00,5.00,1,100.0,10.000000,100.000000,100.000000,9.150588,100.000000,100.000000
34,Saymon Italo Cordeiro de Moura,47,1.875,0.00,10.00,0.00,1,50.0,9.642857,92.857143,71.428571,2.352941,92.857143,92.857143
35,Victor Emanuel Cunha Morais,42,2.920,4.51,10.00,10.00,1,100.0,9.642857,96.428571,98.214286,10.000000,96.428571,96.428571
36,Willian Jorge Sousa Furtado,52,5.820,10.00,10.00,0.00,1,50.0,10.000000,100.000000,75.000000,9.510000,100.000000,100.000000
37,Ycaro Yan Lourenço Santos,28,3.955,10.00,10.00,10.00,3,100.0,9.642857,96.428571,98.214286,5.520000,96.428571,96.428571

In [13]:
df_atividade_6 = pd.read_csv('vpl_atividade_06_com_engajamento.csv')

df_atividade_6

analise_notas_df = analise_notas_df.merge(df_atividade_6[['NOME_ALUNO', 'Media_Notas']], 
                                          on='NOME_ALUNO', how='left', suffixes=('_atividade_6', '_atividade_6'))

analise_notas_df.rename(columns={'Media_Notas': 'Nota6'}, inplace=True)


analise_notas_df = analise_notas_df.merge(df_atividade_6[['NOME_ALUNO', 'TAXA_ENGAJAMENTO']], 
                                          on='NOME_ALUNO', how='left', suffixes=('_atividade_6', '_atividade_6'))

analise_notas_df.rename(columns={'TAXA_ENGAJAMENTO': 'engajamento_n6'}, inplace=True)

analise_notas_df['engajamento_n6_media'] = (analise_notas_df['engajamento_n5'] + analise_notas_df['engajamento_n6'])/2

analise_notas_df

,NOME_ALUNO,USERID,NotaCP,Nota1,Nota2,Nota3,Experiencia,Engajamento_ant,Nota4,engajamento_n4,engajamento_n4_media,Nota5,engajamento_n5,engajamento_n5_media,Nota6,engajamento_n6,engajamento_n6_media
0,Alexandre Henrique Oliveira de Sousa,63,0.000,10.00,10.00,0.00,2,66.0,10.000000,78.571429,72.285714,9.411765,78.571429,78.571429,7.777778,55.555556,67.063492
1,Alisson vaz silva,56,7.275,10.00,10.00,10.00,2,100.0,8.928571,85.714286,92.857143,8.196471,85.714286,85.714286,10.000000,100.000000,92.857143
2,Antonio Wills da Silva Santos,41,5.410,10.00,10.00,10.00,1,100.0,8.928571,100.000000,100.000000,10.000000,100.000000,100.000000,10.000000,100.000000,100.000000
3,Ávila da Conceição Araújo,25,3.125,5.00,10.00,10.00,2,83.5,10.000000,100.000000,91.750000,9.243529,100.000000,100.000000,6.666667,55.555556,77.777778
4,Carlos Eduardo Lima Coutinho,26,7.695,4.51,10.00,10.00,3,83.5,10.000000,100.000000,91.750000,10.000000,100.000000,100.000000,10.000000,100.000000,100.000000
5,Crisfieldy Aristodenes Feitoza Ribeiro,20,3.330,5.00,10.00,0.00,3,50.0,10.000000,92.857143,71.428571,10.000000,92.857143,92.857143,10.000000,55.555556,74.206349
6,Danielly dos Santos Almeida,43,3.330,4.51,10.00,10.00,2,83.5,4.642857,100.000000,91.750000,9.362941,100.000000,100.000000,10.000000,100.000000,100.000000
7,Debriane da Silva Conceição,65,0.000,0.00,0.00,0.00,3,0.0,3.571429,71.428571,35.714286,6.015882,71.428571,71.428571,7.222222,55.555556,63.492063
8,Durval Veloso Barbosa Filho,40,0.830,10.00,0.00,0.00,2,40.0,7.500000,92.857143,66.428571,9.528824,92.857143,92.857143,10.000000,100.000000,96.428571
9,Evelly Victory Vieira Pinto,50,6.240,5.00,8.75,5.00,2,100.0,10.000000,100.000000,100.000000,9.411765,100.000000,100.000000,10.000000,44.444444,72.222222
10,Francisco Leonel Ferreira dos Santos,35,6.660,10.00,10.00,10.00,2,83.5,8.928571,100.000000,91.750000,10.000000,100.000000,100.000000,10.000000,100.000000,100.000000
11,Gabriel Antonio Assunção Oliveira,36,5.615,10.00,10.00,10.00,3,83.5,9.642857,96.428571,89.964286,8.529412,96.428571,96.428571,8.888889,100.000000,98.214286
12,Gabriel Viana Da Costa,34,5.410,4.50,10.00,10.00,1,100.0,10.000000,100.000000,100.000000,9.705882,100.000000,100.000000,8.888889,100.000000,100.000000
13,Guilherme Oliveira de Menezes,48,7.285,4.51,10.00,10.00,1,83.5,10.000000,100.000000,91.750000,10.000000,100.000000,100.000000,10.000000,22.222222,61.111111
14,Gustavo Marinho Santos,53,1.875,5.00,8.75,0.00,1,40.0,1.071429,10.714286,25.357143,NaN,10.714286,10.714286,NaN,NaN,NaN
15,Gustavo Neves,45,1.670,0.00,0.00,0.00,1,20.0,7.142857,78.571429,49.285714,4.117647,78.571429,78.571429,2.222222,66.666667,72.619048
16,Heráclito Thiago de Castro Santos,39,0.000,5.00,10.00,10.00,3,66.5,10.000000,100.000000,83.250000,10.000000,100.000000,100.000000,10.000000,100.000000,100.000000
17,Hipócrates Augusto Soares Brandão Galvão de Ca...,38,5.830,10.00,10.00,8.75,4,100.0,9.642857,92.857143,96.428571,8.088235,92.857143,92.857143,6.111111,77.777778,85.317460
18,Isaac Levi Oliveira Chaves,54,4.795,6.25,10.00,5.00,2,83.5,9.642857,96.428571,89.964286,10.000000,96.428571,96.428571,10.000000,100.000000,98.214286
19,Jonas Davi Nogueira Sena,30,4.375,5.00,10.00,8.75,2,100.0,10.000000,100.000000,100.000000,9.117647,100.000000,100.000000,7.222222,88.888889,94.444444
20,José Cássios Costa Torres,22,6.445,10.00,10.00,10.00,2,100.0,10.000000,100.000000,100.000000,10.000000,100.000000,100.000000,10.000000,100.000000,100.000000
21,Juan Pablo de sousa silva,49,5.830,4.51,10.00,10.00,3,100.0,10.000000,100.000000,100.000000,9.411765,100.000000,100.000000,8.888889,55.555556,77.777778
22,Lara Emanuelly da Silva Santos,44,4.514,0.00,10.00,0.00,2,50.0,8.928571,100.000000,75.000000,9.735294,100.000000,100.000000,10.000000,100.000000,100.000000
23,Loyse Kelly Cardoso Diniz,46,1.455,10.00,10.00,10.00,2,83.5,9.642857,96.428571,89.964286,9.852941,96.428571,96.428571,10.000000,100.000000,98.214286
24,Lucas Eduardo Lima Da Silva,51,4.375,5.00,8.75,0.00,1,40.0,9.642857,100.000000,70.000000,8.823529,100.000000,100.000000,10.000000,100.000000,100.000000
25,Luis Eduardo Martins Formiga,57,0.000,5.00,10.00,10.00,4,83.5,10.000000,100.000000,91.750000,8.235294,100.000000,100.000000,7.777778,55.555556,77.777778
26,Luis Felipe Assunção Pereira,27,4.590,5.00,8.75,10.00,1,83.5,9.285714,96.428571,89.964286,9.510000,96.428571,96.428571,7.222222,100.000000,98.214286
27,Mickaela evely Sousa de Freitas,60,0.000,0.00,0.00,0.00,1,0.0,10.000000,100.000000,50.000000,6.598235,100.000000,100.000000,6.666667,55.555556,77.777778
28,Neudson Gabriel C. C. Branco,21,5.205,6.25,10.00,10.00,3,100.0,10.000000,100.000000,100.000000,9.804118,100.000000,100.000000,8.888889,100.000000,100.000000
29,Pedro Victor Soares da Silva Araújo,18,4.505,10.00,10.00,10.00,2,83.5,10.000000,96.428571,89.964286,10.000000,96.428571,96.428571,10.000000,100.000000,98.214286
30,Raislan Ítalo de Sousa da Silva,23,4.505,4.51,10.00,10.00,2,83.5,10.000000,100.000000,91.750000,10.000000,100.000000,100.000000,10.000000,100.000000,100.000000
31,Randerson Sousa de Sá Nunes,29,4.580,5.00,10.00,5.00,2,83.5,10.000000,82.142857,82.821429,3.333529,82.142857,82.142857,8.888889,100.000000,91.071429
32,Roberto Guilhon Rosa Filho,31,4.514,8.75,10.00,0.00,2,50.0,9.642857,85.714286,67.857143,6.421765,85.714286,85.714286,NaN,NaN,NaN
33,Samuel Ryan da Fonseca Anunciação,37,3.750,5.00,10.00,5.00,1,100.0,10.000000,100.000000,100.000000,9.150588,100.000000,100.000000,10.000000,100.000000,100.000000
34,Saymon Italo Cordeiro de Moura,47,1.875,0.00,10.00,0.00,1,50.0,9.642857,92.857143,71.428571,2.352941,92.857143,92.857143,7.777778,66.666667,79.761905
35,Victor Emanuel Cunha Morais,42,2.920,4.51,10.00,10.00,1,100.0,9.642857,96.428571,98.214286,10.000000,96.428571,96.428571,10.000000,100.000000,98.214286
36,Willian Jorge Sousa Furtado,52,5.820,10.00,10.00,0.00,1,50.0,10.000000,100.000000,75.000000,9.510000,100.000000,100.000000,6.666667,55.555556,77.777778
37,Ycaro Yan Lourenço Santos,28,3.955,10.00,10.00,10.00,3,100.0,9.642857,96.428571,98.214286,5.520000,96.428571,96.428571,8.888889,88.888889,92.658730