In [1]:
# Importando as bibliotecas pandas, matplolib e numpy

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

#Iportando o Arquivo CSV para a análise dos dados, 
#Abaixo será gerado um DataFrame para a manipulação usando o Pandas

df_vpl_atividades = pd.read_csv('mdl_vpl.csv')

In [2]:
df_vpl_atividades

,ID,COURSE,NAME,SHORTDESCRIPTION,INTRO,INTROFORMAT,STARTDATE,DUEDATE
0,39,6,Olá Mundo!,NaN,NaN,1,0,1682726400
1,40,6,Questão 01,Faça um programa que leia um número inteiro e ...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400
2,41,6,Questão 02,Faça um programa que leia um número real e o i...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400
3,42,6,Questão 03,Faça um programa que peça ao usuário para digi...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400
4,43,6,Questão 04,Faça um programa que leia um número real e imp...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400
...,...,...,...,...,...,...,...,...
165,205,32,Questão 01,NaN,"<p dir=""ltr"" style=""text-align: left;""></p><sp...",1,0,1686441600
166,206,32,Questão 02,NaN,"<p dir=""ltr"" style=""text-align: left;""></p><sp...",1,0,1686441600
167,207,32,Questão 03,NaN,"<p dir=""ltr"" style=""text-align: left;""></p><sp...",1,0,1686441600
168,208,32,Questão 05,NaN,"<p dir=""ltr"" style=""text-align: left;""></p><sp...",1,0,1686441600
169,209,32,Questão 06,NaN,"<p dir=""ltr"" style=""text-align: left;""></p><sp...",1,0,1686441600

Selecionar apenas as questões da Atividade do Produto Educacional chamado Atividades Iniciais em C

In [3]:
import pandas as pd
from datetime import datetime

# Função para converter timestamp Unix em formato normal
def timestamp_para_data(timestamp):
    return datetime.utcfromtimestamp(timestamp).strftime('%Y-%m-%d %H:%M:%S')

# Aplicar a função para criar uma nova coluna com as datas no formato normal
df_vpl_atividades['DATA_ENTREGA'] = df_vpl_atividades['DUEDATE'].apply(timestamp_para_data)

# Salvar o DataFrame em um arquivo CSV
df_vpl_atividades.to_csv('vpl_atividades.csv', index=False)


# Exibir o DataFrame resultante
df_vpl_atividades

,ID,COURSE,NAME,SHORTDESCRIPTION,INTRO,INTROFORMAT,STARTDATE,DUEDATE,DATA_ENTREGA
0,39,6,Olá Mundo!,NaN,NaN,1,0,1682726400,2023-04-29 00:00:00
1,40,6,Questão 01,Faça um programa que leia um número inteiro e ...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400,2023-04-29 00:00:00
2,41,6,Questão 02,Faça um programa que leia um número real e o i...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400,2023-04-29 00:00:00
3,42,6,Questão 03,Faça um programa que peça ao usuário para digi...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400,2023-04-29 00:00:00
4,43,6,Questão 04,Faça um programa que leia um número real e imp...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400,2023-04-29 00:00:00
...,...,...,...,...,...,...,...,...,...
165,205,32,Questão 01,NaN,"<p dir=""ltr"" style=""text-align: left;""></p><sp...",1,0,1686441600,2023-06-11 00:00:00
166,206,32,Questão 02,NaN,"<p dir=""ltr"" style=""text-align: left;""></p><sp...",1,0,1686441600,2023-06-11 00:00:00
167,207,32,Questão 03,NaN,"<p dir=""ltr"" style=""text-align: left;""></p><sp...",1,0,1686441600,2023-06-11 00:00:00
168,208,32,Questão 05,NaN,"<p dir=""ltr"" style=""text-align: left;""></p><sp...",1,0,1686441600,2023-06-11 00:00:00
169,209,32,Questão 06,NaN,"<p dir=""ltr"" style=""text-align: left;""></p><sp...",1,0,1686441600,2023-06-11 00:00:00

Selecionando apenas as questões da primeira atividade usando VPL

In [4]:

valores_desejados = [40, 41, 40, 41,42,43,44,45,46,47,48,49,50,51,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68]
df_vpl_01 = df_vpl_atividades[df_vpl_atividades['ID'].isin(valores_desejados)]

# Salvar o novo DataFrame em um arquivo CSV
df_vpl_01.to_csv('vpl_cad_atividade01.csv', index=False)


df_vpl_01

,ID,COURSE,NAME,SHORTDESCRIPTION,INTRO,INTROFORMAT,STARTDATE,DUEDATE,DATA_ENTREGA
1,40,6,Questão 01,Faça um programa que leia um número inteiro e ...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400,2023-04-29 00:00:00
2,41,6,Questão 02,Faça um programa que leia um número real e o i...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400,2023-04-29 00:00:00
3,42,6,Questão 03,Faça um programa que peça ao usuário para digi...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400,2023-04-29 00:00:00
4,43,6,Questão 04,Faça um programa que leia um número real e imp...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400,2023-04-29 00:00:00
5,44,6,Questão 05,Faça um programa que leia um número real e imp...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400,2023-04-29 00:00:00
6,45,6,Questão 06,Faça um programa que leia uma temperatura em g...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400,2023-04-29 00:00:00
7,46,6,Questão 07,Faça um programa que leia uma temperatura em g...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400,2023-04-29 00:00:00
8,47,6,Questão 08,Faça um programa que leia uma temperatura em g...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400,2023-04-29 00:00:00
9,48,6,Questão 09,Faça um programa que leia uma temperatura em g...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1682726400,2023-04-29 00:00:00
10,49,6,Questão 10,Faça um programa que leia uma velocidade em km...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1687996800,2023-06-29 00:00:00
11,50,6,Questão 11,Faça um programa que leia uma velocidade em m/...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1687996800,2023-06-29 00:00:00
12,51,6,Questão 12,Faça um programa que leia um valor de volume e...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1687996800,2023-06-29 00:00:00
13,53,6,Questão 13,Faça um programa que leia um valor de volume e...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1687996800,2023-06-29 00:00:00
14,54,6,Questão 14,Leia um valor de área em hectares e apresente-...,"<p dir=""ltr"" style=""text-align: left;"">Leia um...",1,0,1687996800,2023-06-29 00:00:00
15,55,6,Questão 15,Faça um programa em C que realize a leitura de...,"<p dir=""ltr"">Faça um programa em C que realize...",1,0,1687996800,2023-06-29 00:00:00
16,56,6,Questão 16,"Faça um programa em C que leia quatro notas, c...","<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1687996800,2023-06-29 00:00:00
17,57,6,Questão 17,Faça um programa em C que leia um valor em rea...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1687996800,2023-06-29 00:00:00
18,58,6,Questão 18,Faça um programa em C que leia um número intei...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1687996800,2023-06-29 00:00:00
19,59,6,Questão 19,Faça um programa em C que leia um número intei...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1687996800,2023-06-29 00:00:00
20,60,6,Questão 20,Faça um programa em C que leia o tamanho do la...,"<p dir=""ltr"" style=""text-align: left;""></p><p>...",1,0,1689811200,2023-07-20 00:00:00
21,61,6,Questão 21,Faça um programa em C que leia o valor do raio...,"<p dir=""ltr"" style=""text-align: left;""></p><p>...",1,0,1687132800,2023-06-19 00:00:00
22,62,6,Questão 22,"Sejam a e b os catetos de um triângulo, onde a...","<p dir=""ltr"" style=""text-align: left;"">Sejam a...",1,0,1687132800,2023-06-19 00:00:00
23,63,6,Questão 23,Faça um programa em C que leia o valor de um p...,"<p dir=""ltr"" style=""text-align: left;"">Faça um...",1,0,1687219200,2023-06-20 00:00:00
24,64,6,Questão 24,Faça um programa em C que leia o salário de um...,"<p dir=""ltr"" style=""text-align: left;""></p><p>...",1,0,1687219200,2023-06-20 00:00:00
25,65,6,Questão 25,"A importância de R$ 780.000,00 será dividida e...","<p dir=""ltr"" style=""text-align: left;""></p><p>...",1,0,1687219200,2023-06-20 00:00:00
26,66,6,Questão 26,"Uma empresa contrata um programador por R$330,...","<p dir=""ltr"" style=""text-align: left;""></p><p>...",1,0,1687219200,2023-06-20 00:00:00
27,67,6,Questão 27,Faça um programa em C que receba o salário bas...,"<p dir=""ltr"" style=""text-align: left;""></p><p>...",1,0,1687305600,2023-06-21 00:00:00
28,68,6,Questão DESAFIO!,28.\tDESAFIO! Usando apenas as técnicas aprend...,"<p dir=""ltr"" style=""text-align: left;""></p><p>...",1,0,1687305600,2023-06-21 00:00:00